//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Last.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдать админку.
        /// </summary>
        public static string add_admin {
            get {
                return ResourceManager.GetString("add-admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить тэг.
        /// </summary>
        public static string add_tag {
            get {
                return ResourceManager.GetString("add-tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все коллекции.
        /// </summary>
        public static string all_collections {
            get {
                return ResourceManager.GetString("all-collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самые большие коллекции.
        /// </summary>
        public static string biggest_collections {
            get {
                return ResourceManager.GetString("biggest-collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокировать.
        /// </summary>
        public static string block {
            get {
                return ResourceManager.GetString("block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы просматриваете коллекцию.
        /// </summary>
        public static string browse_collection {
            get {
                return ResourceManager.GetString("browse-collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кнопочки.
        /// </summary>
        public static string buttons {
            get {
                return ResourceManager.GetString("buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить тему.
        /// </summary>
        public static string change_theme {
            get {
                return ResourceManager.GetString("change-theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание коллекции.
        /// </summary>
        public static string collection_description {
            get {
                return ResourceManager.GetString("collection-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема коллекции.
        /// </summary>
        public static string collection_theme {
            get {
                return ResourceManager.GetString("collection-theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекции.
        /// </summary>
        public static string collections {
            get {
                return ResourceManager.GetString("collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать коллекцию.
        /// </summary>
        public static string create_collection {
            get {
                return ResourceManager.GetString("create-collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создатель.
        /// </summary>
        public static string creator {
            get {
                return ResourceManager.GetString("creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить коллекцию.
        /// </summary>
        public static string delete_collection {
            get {
                return ResourceManager.GetString("delete-collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете выбрать аватарку перетащив изображение в выделенную область(не обязательно).
        /// </summary>
        public static string dragndrop {
            get {
                return ResourceManager.GetString("dragndrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать коллекцию.
        /// </summary>
        public static string edit_collection {
            get {
                return ResourceManager.GetString("edit-collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эл. почта.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в коллекцию.
        /// </summary>
        public static string goto_collection {
            get {
                return ResourceManager.GetString("goto-collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понравилось.
        /// </summary>
        public static string likes {
            get {
                return ResourceManager.GetString("likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои коллекции.
        /// </summary>
        public static string my_collections {
            get {
                return ResourceManager.GetString("my-collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забрать админку.
        /// </summary>
        public static string remove_admin {
            get {
                return ResourceManager.GetString("remove-admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string repeatPassword {
            get {
                return ResourceManager.GetString("repeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string secondName {
            get {
                return ResourceManager.GetString("secondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать изображение.
        /// </summary>
        public static string select_image {
            get {
                return ResourceManager.GetString("select-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тэги.
        /// </summary>
        public static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недоступны.
        /// </summary>
        public static string unavailable {
            get {
                return ResourceManager.GetString("unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокировать.
        /// </summary>
        public static string unblock {
            get {
                return ResourceManager.GetString("unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пользователя.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to введите комментарий.
        /// </summary>
        public static string write_comment {
            get {
                return ResourceManager.GetString("write-comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите тэг.
        /// </summary>
        public static string write_tag {
            get {
                return ResourceManager.GetString("write-tag", resourceCulture);
            }
        }
    }
}
